[project]
name = "piramid"
version = "0.1.0"
description = "Vector database for agentic applications."
readme = "README.md"
license = { text = "Apache-2.0" }
requires-python = ">=3.10"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
